name: madebycrate
favicon: null
layout_spectrum: 0.4787234
typography_spectrum: 0.4659574
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.9478933
purpose: []
