name: madebycrate
favicon: null
layout_spectrum: 0
typography_spectrum: 0.30552
title: madebycrate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171614'
    - '#685b55'
    - '#343128'
    - '#4a3f39'
    - '#6f7072'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.9478933
purpose: []
